- c++/JNEXT.cpp
Here's the code for JNEXT using cpp.
> Added solution of JNEXT in cpp

- c++/MMAXPER.cpp
- c++/RKS.cpp
- c++/SCUBADIV.cpp
- c++/SUBS.cpp
Added codes for the following problems: 
MMAXPER
RKS
SCUBADIV
SUBS
> Added files

- c++/PRISMA
Calculation of minimum surface area to produce a can (prism) for a given volume.
> PRISMSA - TRIANGULAR PRISM

- python/NGM - A Game with Numbers
Nikifor and Trofim play the following game: they write some positive integer smaller than 2,000,000,000 and take turns one after another. Nikifor is the first to make a move. The turn is made by the following rule: from the written integer any non-zero digit is subtracted, and the new integer replaces the old one on the desk. For example for integer 40534, the next move can be: 40530, 40531 or 40529. The winner is the player who writes zero on the desk.
Write a program to decide who will win if both players do their best.
> NGM - A Game with Numbers

- python/TOANDFRO - To and Fro
Mo and Larry have devised a way of encrypting messages. They first decide secretly on the number of columns and write the message (letters only) down the columns, padding with extra random letters so as to make a rectangular array of letters. For example, if the message is “There’s no place like home on a snowy night” and there are five columns, Mo would write down
t o i o y
h p k n n
e l e a i
r a h s g
e c o n h
s e m o t
n l e w x
Note that Mo includes only letters and writes them all in lower case. In this example, Mo used the character ‘x’ to pad the message out to make a rectangle, although he could have used any letter. Mo then sends the message to Larry by writing the letters in each row, alternating left-to-right and right-to-left. So, the above would be encrypted as …
> TOANDFRO - To and Fro

- python/LASTDIG - The last digit
Nestor was doing the work of his math class about three days but he is tired of make operations a lot and he should deliver his task tomorrow. His math’s teacher gives him two numbers a and b. The problem consist of finding the last digit of the potency of base a and index b. Help Nestor with his problem. You are given two integer numbers: the base a (0 <= a <= 20) and the index b (0 <= b <= 2,147,483,000), a and b both are not 0. You have to find the last digit of a^b.
> LASTDIG - The last digit

- python/ETF - Euler Totient Function
Here In number theory, the totient φ of a positive integer n is defined to be the number of positive integers less than or equal to n that are coprime to n.
Given an integer n (1 <= n <= 10^6). Compute the value of the totient φ.
> ETF - Euler Totient Function

- c++/AE00.cpp
> Added solution of  a problem of SPOJ

- python/BALLSUM.py
Simple math problem includes probability theory as well.
> Add BALLSUM.py

- c++/STONE.cpp
A problem on maths, plane geometry.
> Add STONE.cpp

- c++/RROOT.cpp
A simple problem on maths/geometry.
> Add RROOT.cpp

- c++/PRINT.cpp
A problem to find primes between a given interval.
> Add PRINT.cpp

- SCPC11B.cpp
> Add SCPC11B.cpp

- c++/EC_CONB.cpp
Solution for EC_CONB - Even Numbers
> Add EC_CONB.cpp

- c++/PON.cpp
Solution for PON - Prime or Not
#cryptography #prime-numbers-1 #primality-test
> Add PON.cpp

- c/FCTRL2.c
SIr, I am Vishnu Agarwal 2019BCS-072. I have added FCTRL2.c to C folder
> added FCTRL2.c

- c++/BABTWR.cpp
The solution to BABTWR - Tower of Babylon
> add solution to tower of babylon problem

- c++/ADAGCD.cpp
> Added ADAGCD.cpp

- c++/ADACHES2.cpp
Added the solution to SPOJ problem ADSCHES2
> Added ADACHES2.cpp

- c++/ABA12E.cpp
The C++ Code for the solution of ABA12E.
> Added ABA12E.cpp

- c++/ADAMONEY.cpp
The c++ code to the solution of SPOJ problem ADAMONEY.
> Added ADAMONEY.cpp

- c++/GUMATH2.cpp
Here's the C++ solution to GUMATH2 problem on SPOJ
> Added GUMATH2.cpp

- c++/ASSIGN.cpp
The solution to ASSIGN - Assignments
> add solution to assignments problem

- c++/coins.cpp
The solution to COINS - Bytelandian gold coins
> add solution to bytelandian gold coins problem

- c++/ADADIGIT.CPP
> added adadigit.cpp

- c++/philo.cpp
> Question based on philosopher's stone

- c++/NAKANJ.cpp
Question Link: https://www.spoj.com/problems/NAKANJ/
> Create NAKANJ in C++.
